CSEN-11 Scala style checker was added into project
bwsw/cs-entities pull request #29
Opened 2017-12-05 04:51 UTC by MedvedevBW

2017-12-05 04:52 UTC, MedvedevBW commented
@placccebo

2017-12-05 04:55 UTC, placccebo requested changes

2017-12-05 04:55 UTC, placccebo commented on README.md
>  Simple CloudStack ORM
replace with "Simple CloudStack Entities Framework"

2017-12-05 08:43 UTC, MedvedevBW commented on README.md
>  Simple CloudStack ORM
ok

2017-12-05 08:44 UTC, MedvedevBW commented
@placccebo

2017-12-06 02:39 UTC, placccebo approved these changes

2017-12-06 05:40 UTC, merged