CSEN-22 TagResponse classes were implemented
bwsw/cs-entities pull request #39
Opened 2017-12-07 09:15 UTC by MedvedevBW

2017-12-07 09:27 UTC, MedvedevBW commented
@placccebo

2017-12-07 13:15 UTC, placccebo requested changes

2017-12-07 13:15 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/entities/requests/TagCreateRequest.scala
> +    * @param resourceIds a set with UUID of resources within which tags will be created
a set of resource's UUIDs for which tags will be created

2017-12-07 13:15 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/entities/requests/TagFindRequest.scala
> +class TagFindRequest extends Request {
add a description

2017-12-07 13:15 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/entities/requests/util/UserTagType.scala
> +class UserTagType extends TagType {
add a description

2017-12-07 13:15 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/entities/requests/util/traits/TagType.scala
> +trait TagType {
add a description

2017-12-07 13:15 UTC, placccebo commented on src/test/scala/com/bwsw/cloudstack/entities/requests/TagCreateRequestTestSuite.scala
> +  it should "create a request with predefined parameters" in {
not only predefined parameters

2017-12-08 02:34 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/entities/requests/TagCreateRequest.scala
> +    * @param resourceIds a set with UUID of resources within which tags will be created
ok

2017-12-08 02:34 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/entities/requests/TagFindRequest.scala
> +class TagFindRequest extends Request {
ok

2017-12-08 02:54 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/entities/requests/util/traits/TagType.scala
> +trait TagType {
ok

2017-12-08 02:56 UTC, MedvedevBW commented on src/test/scala/com/bwsw/cloudstack/entities/requests/TagCreateRequestTestSuite.scala
> +  it should "create a request with predefined parameters" in {
ok

2017-12-08 02:59 UTC, placccebo approved these changes

2017-12-08 03:07 UTC, merged